package behWorkerPool

import (
	"turtle/core/lgr"
	"turtle/simulation/simMath"
	"turtle/simulation2/entities"
	"turtle/simulation2/models"
	"turtle/tools"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

var WORKER_OBJECTID = primitive.ObjectID{}

// Mission phases for a logistics transport order.
const (
	MissionToPickup  = 0 // walking to the item at the source
	MissionToDropoff = 1 // carrying the item towards the destination
)

// WorkerMission is a transport order generated by logistics control: pick up an
// item at its current position and deliver it to a drop-off position.
type WorkerMission struct {
	Item      *entities.SimActor
	Pickup    simMath.Position
	Dropoff   *entities.SimEntity
	ActorType string
	Phase     int
}

type Worker struct {
	Name       string
	ActiveTask *models.WorkerTask
	Mission    *WorkerMission
	Aee        tools.AnyEventEmitter
	Actor      *entities.SimActor

	WalkSpeed   float32 // km/h
	Destination *entities.SimEntity
	IsWalking   bool
}

func NewWorker(actor *entities.SimActor) *Worker {
	return &Worker{
		Actor:     actor,
		WalkSpeed: simMath.AVG_WALKING_SPEED,
	}
}

func (self *Worker) GoForActor(actor *entities.SimActor) {
	self.WalkTo(actor.ParentEntity)
}

// StartMission dispatches the worker to pick up an item and deliver it to a
// drop-off position. actorType is carried on the mission for future actor-type
// specific handling.
func (self *Worker) StartMission(item *entities.SimActor, dropoff *entities.SimEntity, actorType string) {
	self.Mission = &WorkerMission{
		Item:      item,
		Pickup:    item.Position,
		Dropoff:   dropoff,
		ActorType: actorType,
		Phase:     MissionToPickup,
	}
	self.WalkTo(item.ParentEntity)
}

// IsFree reports whether the worker can take a new mission.
func (self *Worker) IsFree() bool {
	return self.Mission == nil && !self.IsWalking
}

// WalkTo sets a destination and starts walking towards it on each Step.
func (self *Worker) WalkTo(dest *entities.SimEntity) {
	self.Destination = dest
	self.IsWalking = true
}

// Step advances the worker by one simulation tick, walking towards its
// destination at walking speed until it arrives.
func (self *Worker) Step() {
	if !self.IsWalking {
		return
	}

	position := self.Actor.Position
	remaining := position.MoveTo(self.Destination.Position, self.WalkSpeed)
	self.Actor.UpdatePosition(position)

	// While carrying, the item follows the worker.
	if self.Mission != nil && self.Mission.Phase == MissionToDropoff {
		self.Mission.Item.UpdatePosition(position)
	}

	if remaining == 0 {
		self.arrived()
	}
}

// arrived advances the mission state machine when the worker reaches its
// current destination.
func (self *Worker) arrived() {
	self.IsWalking = false

	if self.Mission == nil {
		return
	}

	targetPosition := self.Mission.Dropoff

	switch self.Mission.Phase {
	case MissionToPickup:
		// Reached the item — carry it towards the drop-off.
		self.Mission.Phase = MissionToDropoff
		self.WalkTo(targetPosition)
	case MissionToDropoff:
		// Delivered.
		self.Mission.Item.UpdatePosition(self.Mission.Dropoff.Position)

		if targetPosition.TakeActor(self.Mission.Item) {
			self.Mission = nil
		} else {
			lgr.Info("Target can't take Item")
		}

	}

}
